### ISSUE TITLE
Проблема CORS

### ISSUE THREAD

**Issue by RomanH98** [nachpav/bp-api#11]
Добрый день! Подскажите, пожалуйста, поддерживается ли вашим API использование в клиенте (браузере)? На данный момент использование на стороне клиента невозможно из-за политики CORS, которая блокирует запрос на bpium.ru. Может есть какая-то возможность избежать блокировки при использовании API (кроме проксирования)

**Comment by nachpav** [comment]
Добрый день!
Использовать можно как в браузере так и в nodejs. Возможность отправки запросов на сторонние ресурсы из браузера зависит от параметров сервера принимающей стороны. Если у вас коробочная версия bpium, то можно прописать в конфигурационном файле параметр CORS=yousite.com или CORS=* что бы принимать запросы из любого источника, в облачной нужно разговаривать с разработчиками платформы, готовы ли они прописать необходимые настройки.

**Comment by RomanH98** [comment]
Да, база облачная, добавлять не готовы. Будем думать надо проксированием, спасибо за ответ!

**Comment by nachpav** [comment]
Пожалуйста!
